name: ecoscan
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0" # ðŸŸ¢ FIXED: Lowered requirement to match your PC

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.2.1
  # State management
  flutter_riverpod: ^3.2.1

  # Firebase core
  firebase_core: ^2.27.0

  # Firebase Auth
  firebase_auth: ^4.17.8

  # Google Sign-In
  google_sign_in: ^6.2.1

  state_notifier: ^0.7.2

  provider: ^6.0.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  camera: ^0.11.3+1
  google_generative_ai: ^0.4.7
  path_provider: ^2.1.5
  path: ^1.9.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # adjusted to be safe for older SDKs

flutter:
  uses-material-design: true

  # ðŸŸ¢ FIXED: Registered your .env file here
  assets:
    - .env
